Import('env')

sources = ['dreams_test1.cpp']
target = 'dreams_test1'

# Build it
objects = env.Object(source = sources)
t =  env.Program( target = target, source = objects)

Clean(t, 'dral_trace.drl.gz')
Default(t)
